import os


TOKEN = os.getenv("BOT_TOKEN")
GIGACHAT_TOKEN = os.getenv("GIGACHAT_TOKEN")
CREATE_TEMPORARY_CHANNEL_ID = int(os.getenv("CREATE_TEMPORARY_CHANNEL_ID"))
TEMPORARY_CHANNELS_CATEGORY_ID = int(os.getenv("TEMPORARY_CHANNELS_CATEGORY_ID"))
